### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Cronosus** [blueyu2/SnapDoors#2]
player say: "i destroy door with stone axe"

crash:
Description: Exception in server tick loop

java.lang.NoSuchMethodError: com.blueyu2.snapdoors.block.BlockDoors.func_149641_N()Ljava/lang/String;
    at com.blueyu2.snapdoors.block.BlockDoors.func_149650_a(BlockDoors.java:128)
    at net.minecraft.block.Block.getDrops(Block.java:1501)
    at net.minecraft.block.Block.func_149690_a(Block.java:656)
    at net.minecraft.block.Block.func_149697_b(Block.java:649)
    at net.minecraft.block.Block.func_149636_a(Block.java:975)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:361)
    at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:273)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:769)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:745)

**Comment by blueyu2** [comment]
What other mods do you have installed?

**Comment by Cronosus** [comment]
here full crash report: http://pastebin.com/jHmxNbwD
server cauldron

**Comment by blueyu2** [comment]
What were you doing that resulted in a crash? Or, what do you mean by 'player say: "i destroy door with stone axe"'?

**Comment by Cronosus** [comment]
server crash, i ask online players what they're doing and one of them destroing door from snapdoors with stone axe...

**Comment by blueyu2** [comment]
The issue has been fixed and the updated version has been uploaded to Curse. Thank you for the bug report and sorry for any downtime it caused.
